// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

// Representation of information where to find CSAF providers as a JSON document.
type Aggregator struct {
	// Contains the URL of the Aggregator JSON schema which the document promises to
	// be valid for.
	Schema AggregatorSchema `json:"$schema"`

	// Provides information about the aggregator.
	Aggregator AggregatorAggregator `json:"aggregator"`

	// Gives the version of the CSAF aggregator specification which the document was
	// generated for.
	Version AggregatorAggregatorVersion `json:"aggregator_version"`

	// Contains the URL for this document.
	CanonicalURL AggregatorURLT `json:"canonical_url"`

	// Contains a list with information from CSAF providers.
	CSAFProviders []AggregatorCSAFProvidersElem `json:"csaf_providers"`

	// Contains a list with information from CSAF publishers.
	CSAFPublishers []AggregatorCSAFPublishersElem `json:"csaf_publishers,omitempty,omitzero"`

	// Holds the date and time when the document was last updated.
	LastUpdated DateTime `json:"last_updated"`

	// Holds the date and time from when this CSAF aggregator file is in a maintained
	// state.
	MaintainedFrom *DateTime `json:"maintained_from,omitempty,omitzero"`

	// Holds the date and time until when this CSAF aggregator file is in a maintained
	// state.
	MaintainedUntil *DateTime `json:"maintained_until,omitempty,omitzero"`
}

// Provides information about the aggregator.
type AggregatorAggregator struct {
	// Provides information about the category of aggregator.
	Category AggregatorAggregatorCategory `json:"category"`

	// Information on how to contact the aggregator, possibly including details such
	// as web sites, email addresses, phone numbers, and postal mail addresses.
	ContactDetails *string `json:"contact_details,omitempty,omitzero" toml:"contact_details"`

	// Provides information about the authority of the aggregator to release the list,
	// in particular, the party's constituency and responsibilities or other
	// obligations.
	IssuingAuthority *string `json:"issuing_authority,omitempty,omitzero" toml:"issuing_authority"`

	// Contains the name of the aggregator.
	Name string `json:"name"`

	// Contains a URL which is under control of the aggregator and can be used as a
	// globally unique identifier for that aggregator.
	Namespace string `json:"namespace"`
}

type AggregatorAggregatorCategory string

const AggregatorAggregatorCategoryAggregator AggregatorAggregatorCategory = "aggregator"
const AggregatorAggregatorCategoryLister AggregatorAggregatorCategory = "lister"

type AggregatorAggregatorVersion string

const AggregatorAggregatorVersionA21 AggregatorAggregatorVersion = "2.1"

// Contains information from a CSAF provider.
type AggregatorCSAFProvidersElem struct {
	// Contains the metadata of a single CSAF provider.
	Metadata MetadataT `json:"metadata"`

	// Contains a list of URLs or mirrors for this CSAF provider.
	Mirrors MirrorsT `json:"mirrors,omitempty,omitzero"`
}

// Contains information from a CSAF publisher.
type AggregatorCSAFPublishersElem struct {
	// Contains the metadata of a single CSAF publisher extracted from one of its CSAF
	// documents.
	Metadata MetadataT `json:"metadata"`

	// Contains a list of URLs or mirrors for this CSAF publisher.
	Mirrors MirrorsT `json:"mirrors"`

	// Contains information about how often the CSAF publisher is checked for new CSAF
	// documents.
	UpdateInterval string `json:"update_interval"`
}

type AggregatorSchema string

const AggregatorSchemaHttpsDocsOasisOpenOrgCSAFCSAFV21SchemaAggregatorJson AggregatorSchema = "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/aggregator.json"

// Contains a URL.
type AggregatorURLT string

// Contains the metadata of a single CSAF issuing party.
type MetadataT struct {
	// Holds the date and time when this entry was last updated.
	LastUpdated DateTime `json:"last_updated"`

	// Provides information about the issuing party for this entry.
	Publisher PublisherT `json:"publisher"`

	// Contains the role of the issuing party according to section 7 in the CSAF
	// standard.
	Role RoleT `json:"role"`

	// Contains the URL of the provider-metadata.json for that entry.
	URL ProviderURLT `json:"url"`
}

// Contains a list of URLs or mirrors for this issuing party.
type MirrorsT []ProviderURLT
