// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

// Contains a URL of a JSON file.
type JsonURLT string

// Representation of metadata information of a CSAF provider as a JSON document.
type Provider struct {
	// Contains the URL of the provider-metadata.json JSON schema which the document
	// promises to be valid for.
	Schema ProviderSchema `json:"$schema"`

	// Contains the URL for this document.
	CanonicalURL ProviderURLT `json:"canonical_url"`

	// Contains a list of used distribution mechanisms.
	Distributions []ProviderDistributionsElem `json:"distributions,omitempty,omitzero"`

	// Holds the date and time when the document was last updated.
	LastUpdated DateTime `json:"last_updated"`

	// Decides whether this file should be linked in the list of a CSAF aggregator.
	ListOnCSAFAggregators bool `json:"list_on_CSAF_aggregators"`

	// Holds the date and time from when the distributions within this CSAF provider
	// are in a maintained state.
	MaintainedFrom *DateTime `json:"maintained_from,omitempty,omitzero"`

	// Holds the date and time until when the distributions within this CSAF provider
	// are in a maintained state.
	MaintainedUntil *DateTime `json:"maintained_until,omitempty,omitzero"`

	// Gives the version of the CSAF provider metadata specification which the
	// document was generated for.
	MetadataVersion ProviderMetadataVersion `json:"metadata_version"`

	// Decides whether the CSAF documents can be mirrored and provided by a CSAF
	// aggregator.
	MirrorOnCSAFAggregators bool `json:"mirror_on_CSAF_aggregators"`

	// Contains a list of OpenPGP keys used to sign CSAF documents.
	PGPKeys []ProviderPublicOpenpgpKeysElem `json:"public_openpgp_keys,omitempty,omitzero"`

	// Provides information about the publisher of the CSAF documents in this
	// repository.
	Publisher PublisherT `json:"publisher"`

	// Contains the role of the issuing party according to section 7 in the CSAF
	// standard.
	Role ProviderRole `json:"role"`
}

// Contains the information of a used distribution mechanism.
type ProviderDistributionsElem struct {
	// Contains all information for directory-based distribution.
	Directory *ProviderDistributionsElemDirectory `json:"directory,omitempty,omitzero"`

	// Contains all information for ROLIE distribution.
	Rolie *ProviderDistributionsElemRolie `json:"rolie,omitempty,omitzero"`
}

// Contains all information for directory-based distribution.
type ProviderDistributionsElemDirectory struct {
	// Provides the TLP label for the directory.
	TLPLabel TLPLabelT `json:"tlp_label"`

	// Contains the base url for the directory-based distribution.
	URL URLT `json:"url"`
}

// Contains all information for ROLIE distribution.
type ProviderDistributionsElemRolie struct {
	// Contains a list of URLs which contain ROLIE category documents.
	Categories []JsonURLT `json:"categories,omitempty,omitzero"`

	// Contains a list of information about ROLIE feeds.
	Feeds []ProviderDistributionsElemRolieFeedsElem `json:"feeds"`

	// Contains a list of URLs which contain ROLIE service documents.
	Services []JsonURLT `json:"services,omitempty,omitzero"`
}

// Contains information about the ROLIE feed.
type ProviderDistributionsElemRolieFeedsElem struct {
	// Holds the date and time when the feed was last updated.
	LastUpdated DateTime `json:"last_updated"`

	// Contains a summary of the feed.
	Summary *string `json:"summary,omitempty,omitzero"`

	// Provides the TLP label for the feed.
	TLPLabel TLPLabelT `json:"tlp_label"`

	// Contains the URL of the feed.
	URL JsonURLT `json:"url"`
}

type ProviderMetadataVersion string

const ProviderMetadataVersionA21 ProviderMetadataVersion = "2.1"

// Contains all information about an OpenPGP key used to sign CSAF documents.
type ProviderPublicOpenpgpKeysElem struct {
	// Contains the fingerprint of the OpenPGP key.
	Fingerprint string `json:"fingerprint"`

	// Contains the URL where the key can be retrieved.
	URL URLT `json:"url"`
}

type ProviderRole string

const ProviderRoleCSAFProvider ProviderRole = "csaf_provider"
const ProviderRoleCSAFPublisher ProviderRole = "csaf_publisher"
const ProviderRoleCSAFTrustedProvider ProviderRole = "csaf_trusted_provider"

type ProviderSchema string

const ProviderSchemaHttpsDocsOasisOpenOrgCSAFCSAFV21SchemaProviderJson ProviderSchema = "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/provider.json"

// Contains a URL of a provider-metadata.json.
type ProviderURLT string

// Provides information about the publisher of the document.
type PublisherT struct {
	// Provides information about the category of publisher releasing the document.
	Category PublisherTCategory `json:"category"`

	// Contains information on how to contact the publisher.
	Contact *PublisherTContact `json:"contact,omitempty,omitzero"`

	// Provides information about the authority of the issuing party to release the
	// document, in particular, the party's constituency and responsibilities or other
	// obligations.
	IssuingAuthority *string `json:"issuing_authority,omitempty,omitzero" toml:"issuing_authority"`

	// Contains the name of the issuing party.
	Name string `json:"name"`

	// Contains a URL which is under control of the issuing party and can be used as a
	// globally unique identifier for that issuing party.
	Namespace string `json:"namespace"`
}

type PublisherTCategory string

const PublisherTCategoryCoordinator PublisherTCategory = "coordinator"
const PublisherTCategoryDiscoverer PublisherTCategory = "discoverer"
const PublisherTCategoryMultiplier PublisherTCategory = "multiplier"
const PublisherTCategoryOther PublisherTCategory = "other"
const PublisherTCategoryTranslator PublisherTCategory = "translator"
const PublisherTCategoryUser PublisherTCategory = "user"
const PublisherTCategoryVendor PublisherTCategory = "vendor"

// Contains information on how to contact the publisher.
type PublisherTContact struct {
	// Contains details regarding ways to reach the publisher, e.g. through web sites,
	// phone numbers, and postal mail addresses.
	Details *string `json:"details,omitempty,omitzero"`

	// Contains the email address that can be used to reach the issuing party.
	Email *string `json:"email,omitempty,omitzero"`

	// Contains a URL pointing to a public OpenPGP key valid for the email of issuing
	// party provided in the sibling property `email`.
	PublicOpenpgpKeyURL *string `json:"public_openpgp_key_url,omitempty,omitzero" toml:"public_openpgp_key_url"`
}

type RoleT = ProviderRole

const RoleTCSAFProvider RoleT = "csaf_provider"
const RoleTCSAFPublisher RoleT = "csaf_publisher"
const RoleTCSAFTrustedProvider RoleT = "csaf_trusted_provider"

type TLPLabelT string

const TLPLabelTAMBER TLPLabelT = "AMBER"
const TLPLabelTAMBERSTRICT TLPLabelT = "AMBER+STRICT"
const TLPLabelTCLEAR TLPLabelT = "CLEAR"
const TLPLabelTGREEN TLPLabelT = "GREEN"
const TLPLabelTRED TLPLabelT = "RED"

// Contains a URL.
type URLT string
