# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

"""Apply narrow, fail-fast repairs to go-jsonschema model output."""

import re
import sys
from pathlib import Path

GENERATED_CVSS_V3_FIELD = '\tCVSSV3 interface{} `json:"cvss_v3,omitempty,omitzero"`'
TYPED_CVSS_V3_FIELD = '\tCVSSV3 CVSSV3 `json:"cvss_v3,omitempty,omitzero"`'
GENERATED_SSVC_V2_SCHEMA_VERSION_FIELD = '\tSchemaVersion string `json:"schemaVersion"`'
TYPED_SSVC_V2_SCHEMA_VERSION_FIELD = '\tSchemaVersion SSVCV2SchemaVersion `json:"schemaVersion"`'

# Exact source matches are intentional. If go-jsonschema changes its output,
# generation must fail so each repair can be reviewed instead of silently lost.
REPLACEMENTS = {
    GENERATED_CVSS_V3_FIELD: TYPED_CVSS_V3_FIELD,
    GENERATED_SSVC_V2_SCHEMA_VERSION_FIELD: TYPED_SSVC_V2_SCHEMA_VERSION_FIELD,
    '\tBaseScore NoneScoreType `json:"baseScore"`': ('\tBaseScore float64 `json:"baseScore"`'),
    '\tBaseSeverity NoneSeverityType `json:"baseSeverity"`': ('\tBaseSeverity CVSSV40Severity `json:"baseSeverity"`'),
    '\tRequired []interface{} `json:"required"`': '\tRequired []string `json:"required"`',
    # These schema definitions use string constants without an explicit type.
    "type CriticalSeverityType interface{}": "type CriticalSeverityType string",
    "type HighSeverityType interface{}": "type HighSeverityType string",
    "type LowSeverityType interface{}": "type LowSeverityType string",
    "type MediumSeverityType interface{}": "type MediumSeverityType string",
    "type NoneSeverityType interface{}": "type NoneSeverityType string",
}

GENERATED_HEADER = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

"""


def prepare_model(path: Path) -> tuple[dict[str, int], int]:
    output_lines: list[str] = []
    replacement_counts = dict.fromkeys(REPLACEMENTS, 0)
    date_time_replacements = 0

    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("// Code generated"):
            continue
        if line == 'import "time"':
            continue
        # time.Time normalizes JSON during a round trip and rejects lowercase
        # RFC 3339 separators. DateTime deliberately retains the source text.
        if "time.Time" in line:
            date_time_replacements += line.count("time.Time")
            line = line.replace("time.Time", "DateTime")
        if line in REPLACEMENTS:
            replacement_counts[line] += 1
            line = REPLACEMENTS[line]
        output_lines.append(line)

    path.write_text(
        GENERATED_HEADER + "\n".join(output_lines) + "\n",
        encoding="utf-8",
    )
    return replacement_counts, date_time_replacements


def replace_once(source: str, old: str, new: str) -> str:
    if source.count(old) != 1:
        msg = f"expected exactly one occurrence of {old!r}"
        raise ValueError(msg)
    return source.replace(old, new)


def type_definition(source: str, name: str) -> str:
    match = re.search(r"^type " + re.escape(name) + r" (?:struct \{.*?^\}|string)$", source, re.MULTILINE | re.DOTALL)
    if match is None:
        msg = f"missing generated type {name}"
        raise ValueError(msg)
    return match.group()


def prepare_public_api(models: dict[str, str]) -> dict[str, str]:
    """Keep equivalent generated types identical and preserve public field names."""
    models = models.copy()
    csaf = models["csaf_generated.go"]
    provider = models["provider_generated.go"]
    for old, shared in (
        ("CSAFDocumentPublisher", "PublisherT"),
        ("CSAFDocumentPublisherCategory", "PublisherTCategory"),
        ("CSAFDocumentPublisherContact", "PublisherTContact"),
    ):
        definition = type_definition(csaf, old)
        if definition.replace("CSAFDocumentPublisher", "PublisherT") != type_definition(provider, shared):
            msg = f"generated publisher types diverged: {old}, {shared}"
            raise ValueError(msg)
        csaf = replace_once(csaf, definition, f"type {old} = {shared}")
    for old, shared in (("CSAFDocumentPublisherCategory", "PublisherTCategory"), ("RoleT", "ProviderRole")):
        left = csaf if old.startswith("CSAF") else provider

        def values(text: str, name: str) -> list[str]:
            return re.findall(r"^const \w+ " + name + r' = ("[^"\n]+")$', text, re.MULTILINE)

        if not values(left, old) or values(left, old) != values(provider, shared):
            msg = f"generated enum values diverged: {old}, {shared}"
            raise ValueError(msg)
    provider = replace_once(provider, "type RoleT string", "type RoleT = ProviderRole")

    for field in ("issuing_authority", "public_openpgp_key_url"):
        provider = replace_once(
            provider,
            f'`json:"{field},omitempty,omitzero"`',
            f'`json:"{field},omitempty,omitzero" toml:"{field}"`',
        )
    csaf = replace_once(
        csaf,
        "type BranchesT []struct {",
        "type BranchesT []Branch\n\n// Branch is one node in the product tree.\ntype Branch struct {",
    )
    provider = replace_once(
        provider,
        '\tPublicOpenpgpKeys []ProviderPublicOpenpgpKeysElem `json:"public_openpgp_keys,omitempty,omitzero"`',
        '\tPGPKeys []ProviderPublicOpenpgpKeysElem `json:"public_openpgp_keys,omitempty,omitzero"`',
    )
    models["aggregator_generated.go"] = replace_once(
        models["aggregator_generated.go"],
        '\tAggregatorVersion AggregatorAggregatorVersion `json:"aggregator_version"`',
        '\tVersion AggregatorAggregatorVersion `json:"aggregator_version"`',
    )
    for field in ("contact_details", "issuing_authority"):
        models["aggregator_generated.go"] = replace_once(
            models["aggregator_generated.go"],
            f'`json:"{field},omitempty,omitzero"`',
            f'`json:"{field},omitempty,omitzero" toml:"{field}"`',
        )
    models["csaf_generated.go"] = csaf
    models["provider_generated.go"] = provider
    return models


def prepare_models(paths: list[Path]) -> None:
    replacement_counts = dict.fromkeys(REPLACEMENTS, 0)
    date_time_replacements = 0
    for path in paths:
        file_counts, file_date_time_replacements = prepare_model(path)
        for generated, count in file_counts.items():
            replacement_counts[generated] += count
        date_time_replacements += file_date_time_replacements

    for generated, count in replacement_counts.items():
        if count != 1:
            msg = f"expected one occurrence of {generated!r}, replaced {count}"
            raise ValueError(msg)
    if date_time_replacements == 0:
        msg = "generated models contain no date-time fields"
        raise ValueError(msg)
    models = prepare_public_api({path.name: path.read_text(encoding="utf-8") for path in paths})
    for path in paths:
        path.write_text(models[path.name], encoding="utf-8")


def main(arguments: list[str]) -> int:
    if not arguments:
        print("usage: prepare-model <generated Go file> ...", file=sys.stderr)
        return 2
    prepare_models([Path(argument) for argument in arguments])
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except Exception as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error
